import asyncio
import time
from typing import Awaitable

from httpx import Response

from bria_internal.common.bria_engine_api import BriaEngineRequest
from bria_internal.common.bria_engine_api.enable_sync_decorator import enable_run_synchronously
from bria_internal.common.bria_engine_api.routes_constants import BriaEngineAPIRoutes
from bria_internal.schemas.status_api import StatusAPIResponse, StatusAPIState


@enable_run_synchronously
async def wait_for_status_request(
    request_id: str, engine_request_client: BriaEngineRequest, timeout: int = 120, interval: int = 2
) -> Awaitable[StatusAPIResponse] | StatusAPIResponse:
    """
    Polling the status from the status API until the request is whether completes or fails

    Args:
        request_id: str - The request ID to wait for (generated by the API)
        engine_request_client: BriaEngineRequest - The engine request client to use (required)
        timeout: int - The timeout in seconds
        interval: int - The interval in seconds

    Returns:
        StatusAPIResponse - The status response body (error or result properties will be populated)

    Raises:
        TimeoutError: If the timeout is reached while waiting for the status request
    """
    start_time = time.time()
    while time.time() - start_time < timeout:
        res: Response = await engine_request_client.get(f"{BriaEngineAPIRoutes.V2_STATUS}/{request_id}")
        data: dict = res.json()

        status_response: StatusAPIResponse = StatusAPIResponse(**data)
        if status_response.status != StatusAPIState.IN_PROGRESS.value:
            return status_response

        await asyncio.sleep(interval)

    raise TimeoutError("Timeout reached while waiting for status request")
